### ISSUE TITLE
mosquitto restart loses mqtt agent topic subscriptions

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#524]
A keepalive and a restart agent procedure would be a solution?

**Comment by AlvaroVega** [comment]
done by https://github.com/telefonicaid/iotagent-ul/blob/329cfebbe7dd6359ef13ca30075349603dfaba9a/lib/bindings/MQTTBinding.js#L134

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/iotagent-json/pull/525

**Comment by Chandradeep-NEC** [comment]
@AlvaroVega 
I'm investigating this issue.

**Comment by AlvaroVega** [comment]
ota-json time=2022-02-21T12:32:54.702Z | lvl=ERROR | corr=4b9c69b5-86eb-466d-956b-2cf1c776c170 | trans=4b9c69b5-86eb-466d-956b-2cf1c776c170 | op=IOTAJSON.MQTT.Binding | from=n/a | srv=XXXX | subsrv=/YYYY | msg=GLOBAL-001: Error subscribing to topics: Error: Connection closed
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at /opt/iotagent-json/node_modules/mqtt/lib/client.js:105:29
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at Array.forEach (<anonymous>)
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at flushVolatile (/opt/iotagent-json/node_modules/mqtt/lib/client.js:103:24)
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at Socket.<anonymous> (/opt/iotagent-json/node_modules/mqtt/lib/client.js:304:5)
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at Socket.emit (events.js:314:20)
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at Socket.EventEmitter.emit (domain.js:506:15)
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at TCP.<anonymous> (net.js:675:12)
pro-core-smc-iota-json-6c7f4c7764-2cvrm smc-iota-json-container     at TCP.callbackTrampoline (internal/async_hooks.js:126:14) | comp=IoTAgent
