### ISSUE TITLE
iotagent breaks after receibe a measure

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/iotagent-json#697]
```
curl --location --request POST 'https://iendpoint/iot/json?i=Mylightpoint-2&k=rcjx0a3hvt0mfmfqd4gwzzwrf' --header 'Content-Type: application/json' --data-raw '{ "actionType": "APPEND", "entities": [ { "id": "urn:ngsi-ld:Streetlight:Streetlight-Mylightpoint-2", "type": "Streetlight", "name": { "type": "Text", "value": "MyLightPoint-test1" }, "description": { "type": "Text", "value": "testdescription" }, "status": { "type": "Text", "value": "connected" }, "dateServiceStarted": { "type": "DateTime", "value": "2020-06-04T09: 55: 02" }, "locationComment": { "type": "Text", "value": "Test1" }, "location": { "type": "geo:json", "value": { "coordinates": [ -87.88429, 41.99499 ], "type": "Point" } }, "address": { "type": "Text", "value": { "streetAddress": "MyStreet" } }, "isRemotelyManaged": { "type": "Integer", "value": 1 }, "installationDate": { "type": "DateTime", "value": "2022-04-17T02: 30: 04" } } ] }'
```

**Comment by AlvaroVega** [comment]
time=2023-02-14T10:33:48.355Z | lvl=INFO | corr=ec6f2e2e-2efa-4173-b60b-67971dde82ef | trans=ec6f2e2e-2efa-4173-b60b-67971dde82ef | op=IoTAgentNGSI.MultiEntityP        lugin | from=n/a | srv=signify | subsrv=/lighting | msg=multiEntityPlugin error {} procesing entity {"actionType":{"type":"string","value":"APPEND"},"entities":        {"type":"string","value":[{"id":"urn:ngsi-ld:Streetlight:Streetlight-Mylightpoint-2","type":"Streetlight","name":{"type":"Text","value":"MyLightPoint-test1"},"d        escription":{"type":"Text","value":"testdescription"},"status":{"type":"Text","value":"connected"},"dateServiceStarted":{"type":"DateTime","value":"2020-06-04T0        9: 55: 02"},"locationComment":{"type":"Text","value":"Test1"},"location":{"type":"geo:json","value":{"coordinates":[-87.88429,41.99499],"type":"Point"}},"addres        s":{"type":"Text","value":{"streetAddress":"MyStreet"}},"isRemotelyManaged":{"type":"Integer","value":1},"installationDate":{"type":"DateTime","value":"2022-04-        17T02: 30: 04"}}]},"id":"Streetlight:Mylightpoint-2","type":"Streetlight"} | comp=IoTAgent
time=2023-02-14T10:33:48.356Z | lvl=INFO | corr=ec6f2e2e-2efa-4173-b60b-67971dde82ef | trans=ec6f2e2e-2efa-4173-b60b-67971dde82ef | op=IoTAgentNGSI.expressionPl        ugin | from=n/a | srv=signify | subsrv=/lighting | msg=expressionPlugin error {} procesing entity {"actionType":{"type":"string","value":"APPEND"},"entities":{"        type":"string","value":[{"id":"urn:ngsi-ld:Streetlight:Streetlight-Mylightpoint-2","type":"Streetlight","name":{"type":"Text","value":"MyLightPoint-test1"},"des        cription":{"type":"Text","value":"testdescription"},"status":{"type":"Text","value":"connected"},"dateServiceStarted":{"type":"DateTime","value":"2020-06-04T09:         55: 02"},"locationComment":{"type":"Text","value":"Test1"},"location":{"type":"geo:json","value":{"coordinates":[-87.88429,41.99499],"type":"Point"}},"address"        :{"type":"Text","value":{"streetAddress":"MyStreet"}},"isRemotelyManaged":{"type":"Integer","value":1},"installationDate":{"type":"DateTime","value":"2022-04-17        T02: 30: 04"}}]},"id":"Streetlight:Mylightpoint-2","type":"Streetlight"} | comp=IoTAgent
time=2023-02-14T10:33:48.356Z | lvl=FATAL | corr=n/a | trans=n/a | op=IoTAgentNGSI.Global | from=n/a | srv=n/a | subsrv=n/a | msg=An unexpected exception has be        en raised. Ignoring: Error: Callback was already called.
    at /opt/iotagent-json/node_modules/async/dist/async.js:969:32
    at update (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/plugins/expressionPlugin.js:163:9)
    at nextTask (/opt/iotagent-json/node_modules/async/dist/async.js:5327:14)
    at next (/opt/iotagent-json/node_modules/async/dist/async.js:5334:9)
    at /opt/iotagent-json/node_modules/async/dist/async.js:972:16
    at update (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/plugins/pluginUtils.js:134:9)
    at nextTask (/opt/iotagent-json/node_modules/async/dist/async.js:5327:14)
    at next (/opt/iotagent-json/node_modules/async/dist/async.js:5334:9)
    at /opt/iotagent-json/node_modules/async/dist/async.js:972:16
    at updateAttribute (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/plugins/attributeAlias.js:98:5)
    at nextTask (/opt/iotagent-json/node_modules/async/dist/async.js:5327:14)
    at next (/opt/iotagent-json/node_modules/async/dist/async.js:5334:9)
    at /opt/iotagent-json/node_modules/async/dist/async.js:972:16
    at emptyMiddleware (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/services/ngsi/ngsiUtils.js:193:9)
    at nextTask (/opt/iotagent-json/node_modules/async/dist/async.js:5327:14)
    at Object.waterfall (/opt/iotagent-json/node_modules/async/dist/async.js:5337:5)
    at applyMiddlewares (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/services/ngsi/ngsiUtils.js:206:15)
    at /opt/iotagent-json/node_modules/async/dist/async.js:66:19
    at nextTask (/opt/iotagent-json/node_modules/async/dist/async.js:5327:14)
    at next (/opt/iotagent-json/node_modules/async/dist/async.js:5334:9)
    at /opt/iotagent-json/node_modules/async/dist/async.js:972:16
    at add (/opt/iotagent-json/node_modules/iotagent-node-lib/lib/services/stats/statsRegistry.js:60:5) | comp=IoTAgent

**Comment by AlvaroVega** [comment]
This is the test case: https://github.com/telefonicaid/iotagent-json/pull/699
